# Generated by Django 2.0.7 on 2018-08-04 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Databases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_alias', models.CharField(max_length=255)),
                ('db_type', models.CharField(max_length=120)),
                ('db_connection_url', models.TextField()),
                ('schemas', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='database',
            name='user',
        ),
        migrations.AlterField(
            model_name='schema',
            name='database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Databases'),
        ),
        migrations.DeleteModel(
            name='Database',
        ),
    ]
