# Generated by Django 2.0.6 on 2018-07-12 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20180712_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='repository_name',
            new_name='repository',
        ),
    ]
