# Generated by Django 2.0.7 on 2018-07-25 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_passwordconfirmation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordConfirmation',
        ),
    ]
