# Generated by Django 2.0.7 on 2018-07-26 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_profile_confirm_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='confirm_password',
        ),
    ]
