# Generated by Django 2.0.7 on 2018-07-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_remove_profile_confirm_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='confirm_password',
            field=models.CharField(default='', max_length=150),
        ),
    ]
