# Generated by Django 2.0.7 on 2018-07-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_profile_confirm_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='database',
            field=models.CharField(default='', max_length=300),
        ),
    ]
