# Generated by Django 2.0.7 on 2018-07-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0013_auto_20180726_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='db_alias',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='database',
            name='db_connection_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='database',
            name='db_type',
            field=models.CharField(max_length=120),
        ),
    ]
