# Generated by Django 2.0.7 on 2018-07-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0014_auto_20180726_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='db_alias',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='database',
            name='db_type',
            field=models.CharField(default='', max_length=120),
        ),
    ]
