# Generated by Django 2.0.7 on 2018-07-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0015_auto_20180726_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='db_connection_url',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='database',
            name='schemas',
            field=models.TextField(default=''),
        ),
    ]
