# Generated by Django 2.0.7 on 2018-07-27 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0017_auto_20180726_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='confirm_password',
        ),
    ]
