# Generated by Django 2.0.7 on 2018-07-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0018_remove_profile_confirm_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
