# Generated by Django 2.0.7 on 2018-07-31 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0019_profile_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='user',
            field=models.ManyToManyField(to='hello.Profile'),
        ),
    ]
