# Generated by Django 2.0.7 on 2018-08-04 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0021_auto_20180804_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='table',
        ),
        migrations.RemoveField(
            model_name='database',
            name='user',
        ),
        migrations.RemoveField(
            model_name='schema',
            name='database',
        ),
        migrations.RemoveField(
            model_name='table',
            name='schema',
        ),
        migrations.DeleteModel(
            name='Column',
        ),
        migrations.DeleteModel(
            name='Database',
        ),
        migrations.DeleteModel(
            name='Schema',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
